#!/bin/bash

#user enter yes or no if they want to see the logs and assigns the answer to the variable a1
read -p "Would you like to view all the MongoDB logs? Yes or No.. " a1

#takes the var a1 passes through the condition statement below if no is selected it'll close out the script else will do a LS -l to see the contents of the dir

if [[ ${a1} = Yes || yes || y ]];
then
echo  -e "Starting Script"
ls -lS /../var/log
ls -lS /../data/logs
ls -lS /../var/log/mongodb-mms-automation/

else

echo -e "not working"

fi


#takes the var Answer a2 and passes it throught the conditional below - compresses messages log older than 12 days
read -p "Would you like to comprise message log files older than two weeks: " a2

if [[ ${a2} = Yes || yes || y ]];
then
echo -e "Starting Compression"
find /../var/log/ -name "messages-*" -not -name "*.gz" -mtime +12 -exec gzip {} \;
ls -l /../var/log/

else

echo -e "No files over 12 days"

fi

#take the var answer a3 passes it through the conditinal below - remove all log from var/log var/log/mongodb & var/log/mongodb-mms-automation older than 24 days
read -p "Would you like to remove all logs older than 24 days" a3

if [[ ${a3} = y || yes || Yes ]];
then
echo -e ".... Rmoving old logs ...."
echo -e ".........................."

find /../var/log * -name "*.gz" -type f -mtime +24 -delete
find /../var/log/mongodb * -name "*.gz" -type f -mtime +24 -delete
find /../var/log/mongodb-mms-automation * -name "*.gz" -type f -mtime +24 -delete

echo -e "... Script Finshed ..."
echo -e "......................"

else
echo -e "no value entered"
fi

read -p "Would you like to view the dir to ensure script ran successfully? " a3

if [[ ${a3} = y ]];
then
ls -l /../var/log
ls -l /../var/log/mongodb
ls -l /../var/log/mongodb-mms-automation

else
echo -e "Closing Script"

fi
